name: komodo_dex
description: Multicoin Wallet with DEX gateway

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.5.3

environment:
  sdk: ">=2.3.0 <3.0.0"

# We're using specific (pinned) plugin versions in order to help us review the dependency upgrades.
# KomodoPlatform plugin upgrades should be created as new branches, with PR into master;
# commits from such branches can be referenced in this YAML (ref) under a TODO section that mentions the branch.
# cf. https://github.com/ca333/komodoDEX/pull/695#issuecomment-592236296

dependencies:
  flutter: # flutter.dev
    sdk: flutter

  flutter_localizations: # flutter.dev
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  # https://github.com/flutter/cupertino_icons
  # Secure code reviewed
  cupertino_icons: 1.0.4 # flutter.dev (Note: Supports null safety)

  # flutter_cupertino_localizations: ^1.0.1

  # https://pub.dev/packages/audioplayers
  audioplayers: 0.20.1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/audioplayers.git
      #ref: 859c88c2c3fe926bdbb6e5e729d3c16d088be76a

  # https://pub.dev/packages/file_picker
  file_picker: 4.2.3 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/flutter_file_picker.git
      #ref: 627c0a31b22026809cea3c5cb3c0a81d2a632117

  # https://pub.dev/packages/path_provider
  # https://github.com/flutter/plugins
  path_provider: 2.0.7 # flutter.dev (Note: Supports null safety)

  # https://pub.dev/packages/provider
  provider: 6.0.1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: https://github.com/KomodoPlatform/provider
      #ref: 0c1394af0ae2422dba43f5d36f0e45ea75f849a3

  # origin https://pub.dev/packages/encrypt
  encrypt: 5.0.1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: https://github.com/KomodoPlatform/encrypt
      #ref: 4.0.3

dev_dependencies:
  flutter_driver: # flutter.dev
    sdk: flutter
  flutter_test: # flutter.dev
    sdk: flutter

  # recommended linter rules
  flutter_lints: 1.0.4 # flutter.dev (Note: Supports null safety)

  test: 1.17.12 # dart.dev (Note: Supports null safety)

  mockito: 5.0.16 # dart.dev (Note: Supports null safety)
  http: 0.13.4 # dart.dev (Note: Supports null safety)
  qr_flutter: 4.0.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/qr.flutter.git
      #ref: 587c969052f37d9fc0f14801aba241bffbc1ea84
  auto_size_text: 3.0.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/auto_size_text.git
      #ref: a2cb00e548916731f5c4c241d79a93419a4f9447

  # barcode_scan was discontinued, I was originally going to replace it with a fork
  # but instead decided to replace with a completely new plugin
  qr_code_scanner: 0.6.1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)

  shared_preferences: 2.0.8 # flutter.dev (Note: Supports null safety)
  bip39: 1.0.6 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/ca333/bip39-dart.git
      #ref: 3bee3eedb28ba5ae1af82873c8e5b6f32038b8a1
  pin_code_view: # SECURE REVIEW REQUIRED: reviewed c0b6516 (Note: DOES NOT support null safety)
    git:
      url: git://github.com/KomodoPlatform/pin_code_view.git
      ref: d471b040206870b002cf0154772c1bca4c5dfe46
  crypto: 3.0.1 # dart.dev (Note: Supports null safety)
  # intl_translation causes version solving problems
  # it also seems to haven't been updated in a while
  # therefore it was switched for a fork that is more up-to-date
  intl_generator: 0.2.1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)

  bs58check: 1.0.2 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/bs58check-dart.git
      #ref: e313f58289d5f4be711a6b430b7f3bb96712c6cc
  url_launcher: 6.0.13 # flutter.dev (Note: Supports null safety)
  share: 2.0.4 # flutter.dev (Note: Supports null safety)
  # https://pub.dev/packages/local_auth, canCheckBiometrics, getAvailableBiometrics
  local_auth: 1.1.8 # flutter.dev (Note: Supports null safety)
  flutter_svg: 0.23.0+1 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/flutter_svg.git
      #ref: 03ed93a576381f2369bd05f8b833a2273705fe69

  # keccak hasn't been updated since 2019 and its dependencies can't be solved
  # keccak: 1.0.3 # 1.0.3 - DONE: Secure code reviewed 4202080 (1.0.3)
    #git:
      #url: git://github.com/KomodoPlatform/keccak.git
      #ref: 420208090228f49237e080a31d1b627ec454d1cd
  timeago: 3.1.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/timeago.dart.git
      #path: timeago/
      #ref: 9aeb58544067d4a2cc480da3741db9c35d1f36f3
  sqflite: 2.0.0+4 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/sqflite.git
      #path: sqflite/
      #ref: 8da4eefdd8b13dfe7eedbd5dea1c1dded7d04acf
  carousel_slider: 4.0.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/flutter_carousel_slider.git
      #ref: 115ce460e6d6e8382e97f6f2e2ad39d90d6485d7
  flutter_secure_storage: 5.0.2 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/flutter_secure_storage.git
      #ref: eef67d3d006b2c53453df183f7d4ac081948e110
  uuid: 3.0.5 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/dart-uuid.git
      #ref: 981adcac181443e3def4ced76a43b96c534e68ce
  # connectivity has been deprecated and replaced by a Flutter Community Plus Plugin
  connectivity_plus: 2.0.3 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
  flutter_slidable: 1.1.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: https://github.com/KomodoPlatform/flutter_slidable.git
      #ref: 27bbe0dfa9866ae01e8001267e873221ef5fbd67
  # package_info has been deprecated and replaced by a Flutter Community Plus Plugin
  package_info_plus: 1.3.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
  flutter_launcher_icons: 0.9.2 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/flutter_launcher_icons.git
      #ref: c2584ef5b381e7343dfa18acddae9becdabd9727
  decimal: 1.3.0 # READY FOR SECURE CODE REVIEW (Note: Supports null safety)
    #git:
      #url: git://github.com/KomodoPlatform/dart-decimal.git
      #ref: 93fcaabe2da686b1987a351a03a70e86edf6504f

  # MRC: Argon2 algo was our only remaining use of flutter_sodium, so I have switched
  # to dargon2_flutter, which does only Argon2, therefore dropping our dependency on
  # flutter_sodium completely

  dargon2_flutter:
    git:
      url: https://github.com/KomodoPlatform/dargon2
      ref: update-dependencies
      path: dargon2_flutter/dargon2_flutter/

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/branding/logo_app.png"
  image_path_android: "assets/branding/logo_app.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/branding/
  - assets/branding/svg/
  - assets/audio/
  - assets/mocks/
  - assets/currency-flags/
  - assets/language-flags/
  - assets/coin-icons/
  - assets/svg/
  - assets/svg_light/
  - assets/swap_share/
  - assets/coins_init_mm2.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Monospace
      fonts:
        - asset: fonts/Monospace/RobotoMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
