name: komodo_dex
description: Multicoin Wallet with DEX gateway

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.19

environment:
  sdk: ">=2.3.0 <3.0.0"

# We're using specific (pinned) plugin versions in order to help us review the dependency upgrades.
# KomodoPlatform plugin upgrades should be created as new branches, with PR into master;
# commits from such branches can be referenced in this YAML (ref) under a TODO section that mentions the branch.
# cf. https://github.com/ca333/komodoDEX/pull/695#issuecomment-592236296

dependencies:
  flutter: # flutter.dev
    sdk: flutter

  flutter_localizations: # flutter.dev
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  # https://github.com/flutter/cupertino_icons
  # Secure code reviewed
  cupertino_icons: 0.1.3 # flutter.dev

  # flutter_cupertino_localizations: ^1.0.1

  # https://pub.dev/packages/audioplayers
  audioplayers: # 0.14.0 - DONE: Secure code reviewed 859c88c
    git:
      url: git://github.com/KomodoPlatform/audioplayers.git
      ref: 859c88c2c3fe926bdbb6e5e729d3c16d088be76a
  
  # https://pub.dev/packages/file_picker
  file_picker: # 1.4.3+2 - DONE: Secure code reviewed b68ee11
    git:
      url: git://github.com/KomodoPlatform/flutter_file_picker.git
      ref: b68ee11c6ac117460ffa0c96b13ac4b89f2386f7

  # https://pub.dev/packages/path_provider
  # https://github.com/flutter/plugins
  path_provider: 1.6.0 # flutter.dev

  # https://pub.dev/packages/provider
  provider: # 4.0.4 - DONE: Secure code reviewed 0c1394a
    git:
      url: https://github.com/KomodoPlatform/provider
      ref: 0c1394af0ae2422dba43f5d36f0e45ea75f849a3

dev_dependencies:
  flutter_driver: # flutter.dev
    sdk: flutter
  flutter_test: # flutter.dev
    sdk: flutter
  test: 1.9.4 # dart.dev
  mockito: 4.1.1 # dart.dev
  http: 0.12.0+4 # dart.dev
  qr_flutter: # 3.2.0 - DONE: Secure code reviewed diff 60b20d1 (2.0.0) 587c969 (3.2.0) - DONE: sub dependencies reviewed: qr-dart (7a1d379)
    git:
      url: git://github.com/KomodoPlatform/qr.flutter.git
      ref: 587c969052f37d9fc0f14801aba241bffbc1ea84
  auto_size_text: # 2.1.0 - DONE: Secure code reviewed diff 2b3ed87 ( 1.1.2) a2cb00 (2.1.0)
    git:
      url: git://github.com/KomodoPlatform/auto_size_text.git
      ref: a2cb00e548916731f5c4c241d79a93419a4f9447
  barcode_scan: # 2.0.1 - DONE: Secure code reviewed diff b2900df (1.0.0) a4a010c (2.0.1)
    git:
      url: git://github.com/KomodoPlatform/flutter_barcode_reader.git
      ref: a4a010ca31b67d6ef331786bb93d79cb71f1f327
  shared_preferences: 0.5.6+1 # flutter.dev
  bip39: # 1.0.3 - DONE: Secure code reviewed dbd846b (1.0.3) - DONE: sub dependencies reviewed
    git: 
      url: git://github.com/KomodoPlatform/bip39-dart.git
      ref: dbd846b743eab3b21f3ef56abc958305be54761a
  pin_code_view: # DONE: Secure code reviewed c0b6516
    git:
      url: git://github.com/KomodoPlatform/pin_code_view.git
      ref: c0b6516aae9a3321fcce7391447351ad73a50f0a
  # share: ^0.6.0+1
  crypto: 2.1.3 # dart.dev
  intl_translation: 0.17.9 # dart.dev
  bs58check: # 1.0.1 - DONE: Secure code reviewed 2889fa8 (1.0.1)
    git:
      url: git://github.com/KomodoPlatform/bs58check-dart.git
      ref: 2889fa8791fd46afb30a9e7984c06b66a6241a44
  url_launcher: 5.4.1 # flutter.dev
  share: # flutter.dev
    git:
      url: git://github.com/KomodoPlatform/plugins.git
      path: packages/share/
      ref: 1494b043d03799dd14e689552d1218918435f9f5
  # https://pub.dev/packages/local_auth, canCheckBiometrics, getAvailableBiometrics
  local_auth: 0.6.1 # flutter.dev
  flutter_svg: # 0.13.1 - DONE: Secure code reviewed diff 39cbfdb (0.13.0+2) a05263d (0.13.1) - DONE: sub dependencies reviewed: path_drawing(1ad9895), xml(6e6547a)
    git:
      url: git://github.com/KomodoPlatform/flutter_svg.git
      ref: a05263d56aa8745405b01df452332d03a758e40d
  keccak: # 1.0.3 - DONE: Secure code reviewed 4202080 (1.0.3)
    git:
      url: git://github.com/KomodoPlatform/keccak.git
      ref: 420208090228f49237e080a31d1b627ec454d1cd
  timeago: # 2.0.26 - DONE: Secure code reviewed 9aeb585 (2.0.26)
    git:
      url: git://github.com/KomodoPlatform/timeago.dart.git
      path: timeago/
      ref: 9aeb58544067d4a2cc480da3741db9c35d1f36f3
  sqflite: # 1.2.2+1 - DONE: Secure code reviewed diff 3cd583b (1.1.2-dev) 8da4eef (1.2.2+1) - DONE: sub dependencies reviewed: process_run(129f744), tekartik_travis_ci_flutter(83a30d5)
    git:
      url: git://github.com/KomodoPlatform/sqflite.git
      path: sqflite/
      ref: 8da4eefdd8b13dfe7eedbd5dea1c1dded7d04acf
  carousel_slider: # 1.4.1 - DONE: Secure code reviewed diff cec5240 (1.3.1) 115ce46 (1.4.1)
    git:
      url: git://github.com/KomodoPlatform/flutter_carousel_slider.git
      ref: 115ce460e6d6e8382e97f6f2e2ad39d90d6485d7
  flutter_secure_storage: # 3.3.1+2 - DONE: Secure code reviewed diff 31c34d6 (3.2.1+1) eef67d3 (3.3.1+2)
    git:
      url: git://github.com/KomodoPlatform/flutter_secure_storage.git
      ref: eef67d3d006b2c53453df183f7d4ac081948e110
  uuid: # 2.0.4 - DONE: Secure code reviewed diff 1b7db8f (2.0.1) 981adca (2.0.4)
    git: 
      url: git://github.com/KomodoPlatform/dart-uuid.git
      ref: 981adcac181443e3def4ced76a43b96c534e68ce
  connectivity: 0.4.6+2 # flutter.dev
  flutter_slidable: # 0.5.4 - DONE: Secure code reviewed diff 9bf12c (0.5.3) 27bbe0d (0.5.4)
    git: 
      url: https://github.com/KomodoPlatform/flutter_slidable.git
      ref: 27bbe0dfa9866ae01e8001267e873221ef5fbd67
  password: # 1.0.0 - DONE: Secure code reviewed dbf924d (1.0.0)
    git:
      url: git://github.com/KomodoPlatform/password-dart.git
      ref: dbf924dab19d6123bc0f64f5c582b3f26a71d7b9
  package_info: 0.4.0+13 # flutter.dev
  flutter_launcher_icons: # 0.7.4 - DONE: Secure code reviewed diff 869b629 (0.7.2+1) c2584ef (0.7.4)
    git:
      url: git://github.com/KomodoPlatform/flutter_launcher_icons.git
      ref: c2584ef5b381e7343dfa18acddae9becdabd9727
  decimal: # 0.3.5 - DONE: Secure code reviewed 93fcaab (0.3.5)
    git:
      url: git://github.com/KomodoPlatform/dart-decimal.git
      ref: 93fcaabe2da686b1987a351a03a70e86edf6504f

  # AG: Error `value of type 'UnsafePointer<_>' has no member 'bindMemory'`
  # means that flutter_sodium is using SWIFT 5 code
  # (merged in https://github.com/firstfloorsoftware/flutter_sodium/pull/16).
  # Downgrade to "0.0.9" to fix.
  # I thought about upgrading the flutter project to Swift 5,
  # but Xcode 10.1 on our Mac CI server only supports Swift 4.2
  # (cf. https://www.swiftprogrammer.info/swift5_high_sierra.html: "your best bet is to upgrade your Mac")
  #flutter_sodium: 0.0.9
  #flutter_sodium: 0.0.10

  # flutter_sodium 0.0.11 still has error with latest flutter version 1.14.3
  # while assembling android release:
  # "Execution failed for task ':flutter_sodium:verifyReleaseResources'"
  # This error is caused by using old compileSdkVersion - 27
  # https://github.com/firstfloorsoftware/flutter_sodium/issues/28
  # Our fork has a fixed compileSdkVersion - 28:
  # https://github.com/KomodoPlatform/flutter_sodium
  #flutter_sodium: ^0.0.11
  # NB: We'll likely need libsodium for EdDSA gossip signatures
  # TODO: selfhost libsodium-jni (android implementation depends on AAR library from https://github.com/joshjdevl/libsodium-jni)
  flutter_sodium: # 0.0.11 - DONE: Secure code reviewed 3d6f8d8 (0.0.11) - TODO: read ^
    git:
      url: git://github.com/KomodoPlatform/flutter_sodium.git
      ref: 3d6f8d89b4e5f5fbb46b0f230a760b3930c57a39

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/logo_kmd.png"
  image_path_android: "assets/logo_kmd.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/audio/
  - assets/mocks/
  - assets/currency-flags/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Monospace
      fonts:
        - asset: fonts/Monospace/RobotoMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
