name: komodo_dex
description: Multicoin Wallet with DEX gateway

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.6.2

publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

# We're using specific (pinned) plugin versions in order to help us review the dependency upgrades.
# KomodoPlatform plugin upgrades should be created as new branches, with PR into master;
# commits from such branches can be referenced in this YAML (ref) under a TODO section that mentions the branch.
# cf. https://github.com/ca333/komodoDEX/pull/695#issuecomment-592236296

dependencies:
  flutter: # flutter.dev
    sdk: flutter

  flutter_localizations: # flutter.dev
    sdk: flutter

  #-----Flutter first party packages-----
  # collection: ^1.15.0-nullsafety.4 # Auto import by Dart null safety migration tool. Replaced with own util.


  #-----flutter.dev, dart.dev--------


  path_provider: ^2.0.13 # flutter.dev (Note: Supports null safety)

  shared_preferences: ^2.0.18 # flutter.dev (Note: Supports null safety)

  url_launcher: ^6.1.10 # flutter.dev (Note: Supports null safety)

  share: 2.0.4 # flutter.dev (Note: Supports null safety)

  local_auth: ^2.1.6 # flutter.dev (Note: Supports null safety)

  http: ^0.13.5 # dart.dev (Note: Supports null safety)

  crypto: 3.0.2 # dart.dev (Note: Supports null safety)

  # TODO: Security audit and switch to locked version github repo source before release.
  # This is so that we ensure we are developing with the latest version of the package
  # before locking it down to a specific version on GitHub. Also makes version 
  # upgrades/conflits easier to resolve.
  hydrated_bloc: 
    ^9.1.0 
    # git:
    #   url: https://github.com/felangel/bloc.git
    #   path: packages/hydrated_bloc/
    #   ref: 021aa895be66f5fea566c03f276a094ae9ceb06e #9.0.0 (Note: Supports null safety)

  # TODO: Security audit and switch to locked version github repo source before release.
  flutter_bloc:
    ^8.1.1
    # git:
    #   url: https://github.com/felangel/bloc.git
    #   path: packages/flutter_bloc/
    #   ref: 32d5002fb8b8a1e548fe8021d8468327680875ff #8.1.1 (Note: Supports null safety)
  
  #-------fluttercommunity.dev------

  # TODO: Security audit and switch to locked version github repo source before release.
  formz:
    ^0.5.0+1
    # git:
    #   url: https://github.com/VeryGoodOpenSource/formz.git
    #   ref: 26a22df1e3087976679e44ac2400de363feaa9cb #0.4.1 (Note: Supports null safety)

  # TODO: Security audit and switch to locked version github repo source before release.
  connectivity_plus: # Hasn't been reviewed yet
    ^3.0.3
    # git:
    #   url: https://github.com/KomodoPlatform/plus_plugins.git
    #   path: packages/connectivity_plus/connectivity_plus/
    #   ref: d293b60a77313cc697542724f00186cb09187103 #2.3.6

  #Moved from Git to pub.dev.
  # TODO: Security audit and switch to locked version github repo source. Changed because of conflicts.
  # 1.4.2 -> 3.0.3
  package_info_plus: ^3.0.3


  #------------3rd party-------------

  audioplayers: # last reviewed 859c88c2c3fe926bdbb6e5e729d3c16d088be76a
    git:
      url: https://github.com/KomodoPlatform/audioplayers.git
      path: packages/audioplayers/
      ref: 9b927167b0bc103bee43042c195e881b8f653964 #0.20.0

  # TODO: Security audit and switch to github repo source. Changed because of conflict with
  # background services and local notifications. 4.2.5 -> 5.1.0. Cant upgrade further because
  #  of further conflicts with other packages.
  file_picker: ^5.2.5 # last reviewed 627c0a31b22026809cea3c5cb3c0a81d2a632117 (4.2.5)


  encrypt: # last reviewed b17327a
    git:
      url: https://github.com/KomodoPlatform/encrypt
      ref: 3a42d25b0c356606c26a238384b9f2189572d954 #5.0.1

  qr_flutter: # last reviewed 587c969052f37d9fc0f14801aba241bffbc1ea84
    git:
      url: https://github.com/KomodoPlatform/qr.flutter.git
      ref: e3f8d3d4bbe8661f6c941acde8c9815a876756a3 #4.0.0

  auto_size_text: # last reviewed a2cb00e548916731f5c4c241d79a93419a4f9447
    git:
      url: https://github.com/KomodoPlatform/auto_size_text.git
      ref: 2178f0821132636bc4f0dea1bc4d40a889d8249b #3.0.0

  mobile_scanner: # newly added, never reviewed
    git:
      url: https://github.com/KomodoPlatform/mobile_scanner.git
      ref: 9ecb3d8c0fc34533b007270cd425264c4b446008 #1.1.2

  bip39: # last reviewed 3bee3eedb28ba5ae1af82873c8e5b6f32038b8a1
    git:
      url: https://github.com/KomodoPlatform/bip39-dart.git
      ref: 3633daa2026b98c523ae9a091322be2903f7a8ab #1.0.6

  # TODO: Security audit and switch back to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  # intl_generator: # newly added, wasn't reviewed
  #   git:
  #     url: https://github.com/KomodoPlatform/intl_generator.git
  #     ref: 1d1f98f291b2cffc80f4a2822024b3722312e571 #0.2.1
  intl_generator: ^0.4.1

  # TODO: Security audit and switch back to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  # flutter_svg: # last reviewed 03ed93a576381f2369bd05f8b833a2273705fe69
  #   git:
  #     url: https://github.com/KomodoPlatform/flutter_svg.git
  #     ref: 02b8595a5b1f1d97c8af5e4a2f84e790bcd8b460 #0.23.0+1
  flutter_svg: ^2.0.2

  sqflite: # last reviewed 8da4eefdd8b13dfe7eedbd5dea1c1dded7d04acf
    git:
      url: https://github.com/KomodoPlatform/sqflite.git
      path: sqflite/
      ref: 85d84b6f656764e4a4d6632dcc9913f4f47011e5 #2.0.0+4
  
  # TODO: Security audit and switch back to github repo source for current version 
  
  flutter_secure_storage: # last reviewed eef67d3d006b2c53453df183f7d4ac081948e110
    git:
      url: https://github.com/KomodoPlatform/flutter_secure_storage.git
      path: flutter_secure_storage/
      ref: 26efe91a75228ad8c8626d6eea18f7f3cb21bdd9 #5.0.2
 
  flutter_slidable: # last reviewed 27bbe0dfa9866ae01e8001267e873221ef5fbd67
    git:
      url: https://github.com/KomodoPlatform/flutter_slidable.git
      ref: 175b0735f5577dd7d378e60cfe2fe1ca607df9fa #1.1.0
  
  # TODO: Security audit and switch back to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  # decimal: # last reviewed 93fcaabe2da686b1987a351a03a70e86edf6504f
  #   git:
  #     url: https://github.com/KomodoPlatform/dart-decimal.git
  #     ref: 16aeee1354b74bb83a84e5f37b7b6976a02400df #1.4.0
  decimal: ^2.3.2

  # TODO: Security audit and switch back to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  # dargon2_flutter: # reviewed by MRC at d11f51cab560acf7644ebef402f1996b6f320365 #3.1.0
  #   git:
  #     url: https://github.com/KomodoPlatform/dargon2
  #     path: dargon2_flutter/dargon2_flutter/
  #     ref: d11f51cab560acf7644ebef402f1996b6f320365 
  dargon2_flutter: ^3.2.0


  uuid: # last reviewed 981adcac181443e3def4ced76a43b96c534e68ce
    git:
      url: https://github.com/KomodoPlatform/dart-uuid.git
      ref: c9a37bc675fd3fa715db2d929dc66d15ec09ad27 #3.0.5


  # TODO: Security audit and switch to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  flutter_background_service: ^2.4.6

  # TODO: Security audit and switch to github repo source for current version 
  # (NB! run 'flutter pub upgrade' and check pubspec.lock for current version)
  flutter_local_notifications: ^13.0.0

  # TODO: Security audit and switch to github repo source for current version 
  rational: ^2.2.2

  # TODO: Security audit and switch to github repo source for current version 
  provider: ^6.0.5
  google_fonts: ^4.0.3
  equatable: ^2.0.5
  hive: ^2.2.3
  biometric_storage: ^4.1.3
  beamer: ^1.5.3
  json_annotation: ^4.8.0
  image_picker: ^0.8.7+4
  archive: ^3.3.7

dev_dependencies:
  integration_test:
    sdk: flutter

  # recommended linter rules
  flutter_lints: ^2.0.1 # flutter.dev (Note: Supports null safety)
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  
# dependency_overrides:
#   flutter_glide_recorder:
#     path: /Users/charl/Documents/Glide/flutter_glide_recorder
    
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/branding/logo_app.png"
  image_path_android: "assets/branding/logo_app.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/branding/
  - assets/branding/svg/
  - assets/audio/
  - assets/mocks/
  - assets/currency-flags/
  - assets/language-flags/
  - assets/coin-icons/
  - assets/svg/
  - assets/svg_light/
  - assets/swap_share/
  - assets/coins.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
    - family: Monospace
      fonts:
        - asset: fonts/Monospace/RobotoMono-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
