name: komodo_dex
description: Multicoin Wallet with DEX gateway

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.14

environment:
  sdk: ">=2.3.0 <3.0.0"

# We're using specific (pinned) plugin versions in order to help us review the dependency upgrades.
# KomodoPlatform plugin upgrades should be created as new branches, with PR into master;
# commits from such branches can be referenced in this YAML (ref) under a TODO section that mentions the branch.
# cf. https://github.com/ca333/komodoDEX/pull/695#issuecomment-592236296

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3

  # flutter_cupertino_localizations: ^1.0.1

  audioplayers: 0.13.7

  # https://pub.dev/packages/file_picker
  file_picker: 1.4.3+2

  # https://pub.dev/packages/path_provider
  path_provider: 1.6.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: 1.9.4
  mockito: 4.1.1
  http: 0.12.0+4
  qr_flutter: 2.1.0+55
  auto_size_text: 1.1.2
  barcode_scan: 1.0.0
  shared_preferences: 0.5.6+1
  bip39: 1.0.3
  pin_code_view:
    git:
      url: git://github.com/KomodoPlatform/pin_code_view.git
      # TODO: Branch cupertino-style-pin-code is waiting for security review, https://github.com/KomodoPlatform/pin_code_view/pull/4
      ref: c0b6516aae9a3321fcce7391447351ad73a50f0a
  # share: ^0.6.0+1
  crypto: 2.1.3
  intl_translation: 0.17.9
  bs58check: 1.0.1
  url_launcher: 5.4.1
  share:
    git:
      url: https://github.com/KomodoPlatform/plugins
      path: packages/share/
      ref: 1494b043d03799dd14e689552d1218918435f9f5
  # https://pub.dev/packages/local_auth, canCheckBiometrics, getAvailableBiometrics
  local_auth: 0.6.1
  flutter_svg: 0.13.1
  keccak: 1.0.3
  timeago: 2.0.26
  sqflite: 1.2.1
  carousel_slider: 1.4.1
  flutter_secure_storage: 3.3.1+1
  uuid: 2.0.4
  connectivity: 0.4.6+2
  flutter_slidable: 0.5.4
  password: 1.0.0
  package_info: 0.4.0+13
  flutter_launcher_icons: 0.7.4
  decimal: 0.3.5

  # AG: Error `value of type 'UnsafePointer<_>' has no member 'bindMemory'`
  # means that flutter_sodium is using SWIFT 5 code
  # (merged in https://github.com/firstfloorsoftware/flutter_sodium/pull/16).
  # Downgrade to "0.0.9" to fix.
  # I thought about upgrading the flutter project to Swift 5,
  # but Xcode 10.1 on our Mac CI server only supports Swift 4.2
  # (cf. https://www.swiftprogrammer.info/swift5_high_sierra.html: "your best bet is to upgrade your Mac")
  #flutter_sodium: 0.0.9
  #flutter_sodium: 0.0.10

  # flutter_sodium 0.0.11 still has error with latest flutter version 1.14.3
  # while assembling android release:
  # "Execution failed for task ':flutter_sodium:verifyReleaseResources'"
  # This error is caused by using old compileSdkVersion - 27
  # https://github.com/firstfloorsoftware/flutter_sodium/issues/28
  # Our fork has a fixed compileSdkVersion - 28:
  # https://github.com/KomodoPlatform/flutter_sodium
  #flutter_sodium: ^0.0.11
  flutter_sodium:
    git:
      url: git://github.com/KomodoPlatform/flutter_sodium.git
      ref: 3d6f8d89b4e5f5fbb46b0f230a760b3930c57a39

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/logo_kmd.png"
  image_path_android: "assets/logo_kmd.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  - assets/audio/
  - assets/mocks/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
        - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
